import type { Metadata } from "next";
import { Noto_Sans_KR } from 'next/font/google';
import "./globals.css";

const notoSansKr = Noto_Sans_KR({
    weight: ['100', '300', '400', '500', '700', '900'],
    subsets: ['latin'],
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="w-full h-full">
            <body className={ `w-full h-full ${notoSansKr.className}` }>
                {children}
            </body>
        </html>
    );
}
