/* eslint-disable @next/next/no-sync-scripts */

import type { Metadata } from "next";
import { Noto_Sans_KR } from 'next/font/google';
import "./globals.css";

const notoSansKr = Noto_Sans_KR({
    weight: ['100', '300', '400', '500', '700', '900'],
    subsets: ['latin'],
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="w-full h-full">
            <head>
                <script src={ `https://map.vworld.kr/js/webglMapInit.js.do?version=2.0&apiKey=${process.env.NEXT_PUBLIC_VWORLD_KEY}` }/>
            </head>
            <body className={ `w-full h-full ${notoSansKr.className}` }>
                {children}
            </body>
        </html>
    );
}
